############# English navigation ##############

# Main Navigation

[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
weight = 2
name = "About Us"
hasChildren = true

[[main]]
parent = "About Us"
name = "GĐPT Anôma"
url = "about-us/gdpt-anoma"


[[main]]
parent = "About Us"
name = "Van Hanh Foundation"
url = "about-us/van-hanh-foundation"



# Team List

[[main]]
weight = 4
name = "Important Information"
hasChildren = true


[[main]]
parent = "Important Information"
name = "Our Location"
url = "important-information/our-location"
weight = 1

[[main]]
parent = "Important Information"
name = "Registration"
url = "important-information/registration"
weight = 2

[[main]]
parent = "Important Information"
name = "Liability Waiver"
url = "important-information/liability-waiver"
weight = 3 

# Team List

[[main]]
weight = 4
name = "Our Team"
hasChildren = true

[[main]]
parent = "Our Team"
name = "Huynh Troung"
url = "our-team/huynh-truong/"
weight = 1


[[main]]
parent = "Our Team"
name = "Huynh Troung in Training"
url = "our-team/huynh-truong-in-training/"
weight = 2


[[main]]
parent = "Our Team"
name = "Alumni"
url = "our-team/alumni/"
weight = 3

# Gallery
[[main]]
weight = 5
name = "Gallery"
hasChildren = true



[[main]]
parent = "Gallery"
name = "2009"
url = "gallery/2009/"


[[main]]
parent = "Gallery"
name = "2008"
url = "gallery/2008/"


[[main]]
parent = "Gallery"
name = "2003"
url = "gallery/2003/"

[[main]]
name = "Blog"
url = "/blog"
weight = 6




# Footer menu
[[footer]]
name = "Terms of Service"
url = "terms-of-service/"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 2
