############# English navigation ##############

# Main Navigation

[[main]]
name = "Trang chủ"
url = "/"
weight = 1

[[main]]
weight = 2
name = "Về chúng tôi"
hasChildren = true

[[main]]
parent = "Về chúng tôi"
name = "GĐPT Anôma"
url = "about-us/gdpt-anoma"
weight = 1

[[main]]
parent = "Về chúng tôi"
name = "Van Hanh Foundation"
url = "about-us/van-hanh-foundation"
weight = 2


# Team List

[[main]]
weight = 4
name = "Thông tin quan trọng"
hasChildren = true


[[main]]
parent = "Thông tin quan trọng"
name = "Địa điểm của chúng tôi"
url = "important-information/our-location"
weight = 1

[[main]]
parent = "Thông tin quan trọng"
name = "Sự đăng ký"
url = "important-information/registration"
weight = 2

[[main]]
parent = "Thông tin quan trọng"
name = "Có khả năng tước bỏ"
url = "important-information/liability-waiver"
weight = 3 

# Team List

[[main]]
weight = 4
name = "Đội của chúng tôi"
hasChildren = true

[[main]]
parent = "Đội của chúng tôi"
name = "Huynh Trưởng"
url = "our-team/huynh-truong/"
weight = 1


[[main]]
parent = "Đội của chúng tôi"
name = "Huynh Trưởng trong đào tạo"
url = "our-team/huynh-truong-in-training/"
weight = 2


[[main]]
parent = "Đội của chúng tôi"
name = "Cựu sinh viên"
url = "our-team/alumni/"
weight = 3

# Gallery
[[main]]
weight = 5
name = "Phòng trưng bày"
hasChildren = true



[[main]]
parent = "Phòng trưng bày"
name = "2009"
url = "gallery/2009/"


[[main]]
parent = "Phòng trưng bày"
name = "2008"
url = "gallery/2008/"


[[main]]
parent = "Phòng trưng bày"
name = "2003"
url = "gallery/2003/"

[[main]]
name = "Blog"
url = "/blog"
weight = 6




# Footer menu
[[footer]]
name = "Điều khoản dịch vụ"
url = "terms-of-service/"
weight = 1

[[footer]]
name = "Chính sách bảo mật"
url = "privacy-policy/"
weight = 2
